[package]
authors = ["The Nushell Project Developers"]
description = "Nushell table printing"
repository = "https://github.com/nushell/nushell/tree/main/crates/nu-table"
edition = "2021"
license = "MIT"
name = "nu-table"
version = "0.69.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "table"
path = "src/main.rs"

[dependencies]
nu-ansi-term = "0.46.0"
nu-protocol = { path = "../nu-protocol", version = "0.69.2" }
strip-ansi-escapes = "0.1.1"
atty = "0.2.14"
tabled = { git = "https://github.com/zhiburt/tabled", rev = "3d86a327267da9793c5ad9b48c5d6167bc9c9314", features = ["color"], default-features = false }
json_to_table = { git = "https://github.com/zhiburt/tabled", rev = "970ebc74c437f12ab520a107e617e0428cfea27c", features = ["color"] }
table_to_html = { git = "https://github.com/zhiburt/tabled", rev = "970ebc74c437f12ab520a107e617e0428cfea27c" }
#table_to_html = { path = "../../../tabled/table_to_html" }
serde_json = "*"
